export interface ReqResResponse {
  page: number;
  per_page: number;
  total: number;
  total_pages: number;
  data: User[] | User | UnknownResource[] | UnknownResource;
}

export interface User {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  avatar: string;
}

// Generated by https://quicktype.io

export interface UnknownResource {
  id:            number;
  name:          string;
  year:          number;
  color:         string;
  pantone_value: string;
}

